version: '3'
services:
  api:
    build: .
    ports:
      # - <ports on local os>: <ports on container>
      - 8000:8000
    # env_file:
    #   - ./.env
    environment:
      - DATABASE_HOSTNAME=postgres
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=2611postgres
      - DATABASE_NAME=python_api_development
      - SECRET_KEY="45df44431b3fb8c402bda62e41e203ffe9099f59bee0c8ff0f3f41e334ea8581"
      - ALGORITHM="HS256"
      - ACCESS_TOKEN_EXPIRE_MINUTES=60
    depends_on:
      - postgres
    volumes:
      - ./:/usr/src/app:ro
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_PASSWORD=2611postgres
      - POSTGRES_DB=python_api_development

    volumes:
      - postgres_db:/var/lib/postgresql/data

volumes:
  postgres_db:
