version: "3"

services:
    mysql:
        image: mysql:8
        volumes:
            - ./.mysql:/var/lib/mysql
        restart: unless-stopped
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: ecommerce_db
        networks:
            - net
    phpmyadmin:
        depends_on:
            - mysql
        image: phpmyadmin/phpmyadmin:5
        restart: unless-stopped
        ports:
            - "8080:80"
        environment:
            PMA_HOST: mysql
            MYSQL_ROOT_PASSWORD: password
        networks:
            - net
networks:
    net:
