version: "3.8"
services:
  api:
    build: ./backend
    ports:
      - 3001:3001
    environment:
      DB_URL: mongodb://mongodb:27017/vidly
    depends_on:
      - mongodb
    command: npm start
    # co`mmand: ./docker-entrypoint.sh
  web:
    build: ./frontend
    ports:
      - 3000:3000
    depends_on:
      - api
  web-test:
    build: ./frontend
    command: npm test
    depends_on:
      - api
  mongodb:
    image: mongo:4.0-xenial
    ports:
      - 27017:27017
    volumes:
      - vidly:/data/db
volumes:
  vidly:
